### ISSUE TITLE
Matching highlights with active theme

### ISSUE THREAD

**Issue by nobiot** [nobiot/org-remark#52]
Original: https://github.com/nobiot/org-transclusion/issues/158

@oatmealm, I believe the issue is relevant with Org-remark.

**Comment by nobiot** [comment]
Alternatively, you can do something like the following to define a face that has different colors depending on light or dark themes.

I think I will add this in the manual.

```emacs-lisp
(defface org-remark-highlighter-yellow
  '((((class color) (min-colors 88) (background light))
     :underline "#d0bc00" :background "goldenrod1")
    (((class color) (min-colors 88) (background dark))
     :underline "#d0bc00" :background "DarkGoldenrod4")
    (t
     :inherit highlight))
  "Face for the yellow highlighter pen.")

(org-remark-create "yellow"
                   'org-remark-highlighter-yellow
                   '(CATEGORY "important"))
```

The result looks like this:

![image](https://user-images.githubusercontent.com/12507865/211211273-bff76801-a2dd-4bd5-9033-4cc69e794f99.png)

![image](https://user-images.githubusercontent.com/12507865/211211279-608d3666-6fac-45d3-a7ef-8573f17ed2d6.png)

**Comment by oatmealm** [comment]
Amazing. I'll try it asap.

**Comment by oatmealm** [comment]
Ok, so I'm using the defface as suggested with modus-vivendi/operandi... it seems like the background is overriden by the theme or something else is happening.

describe-face on a highlighted region:

```
There are 3 overlays here:
 From 8462 to 8937
  *org-remark-note-body [Show]
  CATEGORY             "important"
  face                 (:inherit default :underline "gold2")
  help-echo            [Show]
  org-remark-id        "c84bd647"
  org-remark-label     "yellow"
 From 8462 to 8937
  *org-remark-note-body [Show]
  CATEGORY             "important"
  face                 (:inherit default :underline "gold2")
  help-echo            [Show]
  org-remark-id        "c84bd647"
  org-remark-label     "yellow"
 From 8535 to 8597
  face                 hl-line
  priority             -50
  window               nil
```

Though if I run describe-face directly, I'm seeing this:

```
Face: org-remark-highlighter-yellow (sample) (customize this face)

Documentation:
Face for the yellow highlighter pen.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: goldenrod1
        Underline: #d0bc00
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```
![Screenshot from 2023-01-11 14-14-56](https://user-images.githubusercontent.com/68159077/211815541-7b379478-52f3-4a88-8f54-afa411bc7a98.png)
![Screenshot from 2023-01-11 14-14-47](https://user-images.githubusercontent.com/68159077/211815551-2f2ffb27-16ec-4ef9-875a-908167b3a8bb.png)
